language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

# see this page: http://conda.pydata.org/docs/travis.html
install:
  - sudo apt-get update

  # install conda
  - curl -s https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh > miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - . $HOME/miniconda/etc/profile.d/conda.sh
  - hash -r

  # setup conda
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -c conda-forge -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda activate test-environment

  # install test dependencies
  - conda install -c conda-forge --yes --file requirements-dev.txt
  - pip install -e .
  - conda list

before_script:
  - ./dev/lint.sh

script:
  - ./dev/test.sh
